/** @type {import('tailwindcss').Config} */
module.exports = {
  // NOTE: Update this to include the paths to all files that contain Nativewind classes.
  content: [
    "./App.{js,jsx,ts,tsx}",
    "./src/**/*.{js,jsx,ts,tsx}",
    "./components/**/*.{js,jsx,ts,tsx}"
  ],
  presets: [require("nativewind/preset")],
  theme: {
    extend: {
      colors: {
        "surface": "#f8f9ff",
        "on-secondary-fixed": "#001c39",
        "on-tertiary-container": "#aab3b9",
        "tertiary": "#273034",
        "primary-fixed": "#b0f0d6",
        "surface-bright": "#f8f9ff",
        "secondary-container": "#64a8fe",
        "error": "#ba1a1a",
        "tertiary-container": "#3d464b",
        "surface-tint": "#2b6954",
        "inverse-surface": "#213145",
        "on-primary-fixed": "#002117",
        "on-primary-container": "#80bea6",
        "on-tertiary-fixed": "#141d21",
        "primary-fixed-dim": "#95d3ba",
        "on-background": "#0b1c30",
        "background": "#f8f9ff",
        "tertiary-fixed-dim": "#bfc8ce",
        "secondary": "#0060ac",
        "on-primary": "#ffffff",
        "on-secondary-container": "#003c70",
        "surface-container-low": "#eff4ff",
        "inverse-primary": "#95d3ba",
        "on-tertiary": "#ffffff",
        "on-surface": "#0b1c30",
        "primary-container": "#064e3b",
        "error-container": "#ffdad6",
        "surface-container-lowest": "#ffffff",
        "on-surface-variant": "#404944",
        "primary": "#003527",
        "on-error-container": "#93000a",
        "surface-container-high": "#dce9ff",
        "secondary-fixed": "#d4e3ff",
        "surface-container-highest": "#d3e4fe",
        "on-secondary-fixed-variant": "#004883",
        "on-secondary": "#ffffff",
        "on-error": "#ffffff",
        "outline": "#707974",
        "on-primary-fixed-variant": "#0b513d",
        "surface-dim": "#cbdbf5",
        "tertiary-fixed": "#dbe4ea",
        "secondary-fixed-dim": "#a4c9ff",
        "on-tertiary-fixed-variant": "#3f484d",
        "surface-container": "#e5eeff",
        "inverse-on-surface": "#eaf1ff",
        "outline-variant": "#bfc9c3",
        "surface-variant": "#d3e4fe"
      },
      spacing: {
        "margin-edge": "20px",
        "gutter": "16px",
        "stack-md": "12px",
        "stack-sm": "4px",
        "unit": "8px",
        "section-padding": "32px",
        "stack-lg": "24px"
      }
    },
  },
  plugins: [],
};
